services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cachacadb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "3307:3306"
    profiles: ["dev", "prod"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: always
    volumes:
      - products_images:/app/images
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: "/app/config/dev.toml"
    profiles: ["dev"]

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - products_images:/app/images
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: "/app/config/prod.toml"
    profiles: ["prod"]

volumes:
  mysql_data:
  products_images:
  logs:
